language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite
install: pip install passlib pycrypto requests mysqlclient psycopg2

script:
  - travis/selftest.sh
